02/21/2025 16:00:25 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:00:25 - CRITICAL - Global - Uncaught Exception
Traceback (most recent call last):
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\main.py", line 1, in <module>
    from api.prediction import router
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\api\prediction.py", line 11, in <module>
    model_path = os.path.join(os.path.dirname(), "comp_model.pkl")
                              ~~~~~~~~~~~~~~~^^
TypeError: dirname() missing 1 required positional argument: 'p'
02/21/2025 16:00:47 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:00:47 - CRITICAL - Global - Uncaught Exception
Traceback (most recent call last):
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\main.py", line 1, in <module>
    from api.prediction import router
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\api\prediction.py", line 13, in <module>
    model = joblib.load(model_path)
  File "C:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\ww\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ~~~~^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\LAKSHAY CHHABRA\\Desktop\\KRMU hackathon\\app\\api\\comp_model.pkl'
02/21/2025 16:01:51 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:01:51 - CRITICAL - Global - Uncaught Exception
Traceback (most recent call last):
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\main.py", line 1, in <module>
    from api.prediction import router
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\api\prediction.py", line 13, in <module>
    model = joblib.load(model_path)
  File "C:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\ww\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ~~~~^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LAKSHAY CHHABRA\\Desktop\\comp_model.pkl'
02/21/2025 16:02:25 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:02:26 - CRITICAL - Global - Uncaught Exception
Traceback (most recent call last):
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\main.py", line 1, in <module>
    from api.prediction import router
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\api\prediction.py", line 14, in <module>
    scaler = joblib.load(scaler)
  File "C:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\ww\Lib\site-packages\joblib\numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\ww\Lib\site-packages\joblib\numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\pickle.py", line 1256, in load
    dispatch[key[0]](self)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\pickle.py", line 1581, in load_stack_global
    self.append(self.find_class(module, name))
                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\pickle.py", line 1622, in find_class
    __import__(module, level=0)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sklearn'
02/21/2025 16:03:52 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:06:55 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:07:39 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:08:27 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:08:45 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:10:41 - ERROR - Global - Failed to connect to Elastic
02/21/2025 16:11:38 - INFO - Global - Connected to Elastic
02/21/2025 16:15:15 - INFO - Global - Connected to Elastic
02/21/2025 16:15:16 - CRITICAL - Global - Uncaught Exception
Traceback (most recent call last):
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\main.py", line 1, in <module>
    from api.prediction import router
  File "c:\Users\LAKSHAY CHHABRA\Desktop\KRMU hackathon\app\api\prediction.py", line 19, in <module>
    async def predict(Task: schema.Task):
                            ^^^^^^^^^^^
AttributeError: module 'schema' has no attribute 'Task'
02/21/2025 16:16:43 - INFO - Global - Connected to Elastic
